"""
Fachada de Entorno de Ejecución de Gram (`gram.environment`).
=============================================================
Reexporta las utilidades del entorno virtual y gestión de paquetes.
"""
from __future__ import annotations

from gram.plugins.environment import (
    activate,
    allow_add,
    allow_list,
    allow_remove,
    clean_cache,
    clean_data,
    clean_temp,
    create,
    ensure,
    get_data_base_dir,
    get_path,
    get_pip_executable,
    get_plugin_data_dir,
    get_plugin_temp_dir,
    get_python_executable,
    get_site_packages,
    get_temp_base_dir,
    install,
    install_plugin_requirements,
    is_active,
    is_created,
    is_library_allowed,
    list_packages,
    reinstall,
    reset,
    reset_allowed_libraries,
    run,
    uninstall,
    update,
)

__all__ = [
    "activate",
    "allow_add",
    "allow_list",
    "allow_remove",
    "clean_cache",
    "clean_data",
    "clean_temp",
    "create",
    "ensure",
    "get_data_base_dir",
    "get_path",
    "get_pip_executable",
    "get_plugin_data_dir",
    "get_plugin_temp_dir",
    "get_python_executable",
    "get_site_packages",
    "get_temp_base_dir",
    "install",
    "install_plugin_requirements",
    "is_active",
    "is_created",
    "is_library_allowed",
    "list_packages",
    "reinstall",
    "reset",
    "reset_allowed_libraries",
    "run",
    "uninstall",
    "update",
]
